# Terraform PR Validation Pipeline
# Validates Terraform code without requiring backend configuration

trigger: none # Don't trigger on direct commits to branches

pr:
  branches:
    include:
      - main
  paths:
    include:
      - "**/*.tf"
      - "**/*.tfvars"
      - "environments/**"
      - "modules/**"

variables:
  TF_VERSION: "1.9.0"
  TF_IN_AUTOMATION: "true"

# UPDATED: Pointing to your new Spot Instance VMSS Pool
pool:
  name: "production-spot-agents"

stages:
  - stage: Validate
    displayName: "Terraform Validation"
    jobs:
      - job: TerraformValidate
        displayName: "Validate Terraform Code"
        steps:
          # Install Terraform
          - script: |
              echo "=== Installing Prerequisites ==="
              sudo apt-get update -y
              sudo apt-get install -y unzip wget

              echo "=== Installing Terraform $(TF_VERSION) === "
              wget -q https://releases.hashicorp.com/terraform/$(TF_VERSION)/terraform_$(TF_VERSION)_linux_amd64.zip
              unzip -q terraform_$(TF_VERSION)_linux_amd64.zip
              sudo mv terraform /usr/local/bin/

              echo "=== Verifying Installation ==="
              terraform version
              echo "âœ… Terraform installed"
            displayName: "Install Terraform & dependencies"

          # Format Check
          - script: |
              echo "=== Terraform Format Check === "
              if ! find . -name "*.tf" -type f | grep -q .; then
                echo "âš ï¸  No .tf files found - skipping"
                exit 0
              fi
              terraform fmt -check -recursive -diff
              echo "âœ… Format check passed"
            displayName: "Format Check"
            continueOnError: false

          # Validate Syntax
          - script: |
              echo "=== Terraform Validation ==="
              TERRAFORM_DIRS=$(find . -name "*.tf" -type f -exec dirname {} \; | sort -u)

              if [ -z "$TERRAFORM_DIRS" ]; then
                echo "âš ï¸  No Terraform files found"
                exit 0
              fi

              for dir in $TERRAFORM_DIRS; do
                echo "ðŸ“ Validating: $dir"
                cd "$dir"
                terraform init -backend=false
                terraform validate
                cd - > /dev/null
              done

              echo "âœ… Validation complete"
            displayName: "Validate Terraform"
            continueOnError: false
